name: Generate API Documentation

on:
  push:
    paths:
      - "yaml/**/*.yaml"
      - "yaml/**/*.yml"
  pull_request:
    paths:
      - "yaml/**/*.yaml"
      - "yaml/**/*.yml"
  workflow_dispatch: # Manual trigger

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate API Documentation
        uses: DomoApps/documentation-generator-action@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          yaml_input_path: "./yaml"
          output_path: "./docs"
          template_path: "default" # Uses action's built-in template
          openai_model: "gpt-4o"
          max_iterations: "5"
          completeness_threshold: "90"
          timeout_minutes: "10"

      - name: Create Pull Request with Documentation
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "📚 Update API documentation from YAML changes"
          title: "📚 Auto-generated Documentation Update"
          body: |
            ## 🤖 Documentation Update

            This PR contains automatically generated documentation from YAML file changes.

            Please review before merging.
          branch: docs/api-update-${{ github.run_number }}
          delete-branch: true
          add-paths: |
            docs/**
